--Drop VIEW [dbo].[VW_CashReceivedTransaction_MH];
CREATE VIEW [dbo].[VW_CashReceivedTransaction_MH] AS 
/*with f_statement_fees as(
 select FEE_AMNT=SF_AMOUNT,SF_FEE_CODE,SF_STATEMENT_NUMBER,SF_PAID_DATE
 from [dbo].[PR1_STATEMENT_FEE] 
 where SF_FEE_CODE in (1,3) --installment fee, eft fee
 --and SF_PAID_DATE between @p_from and @p_to
),
other_fees as (
 select FEE_AMNT=SFQ_FEE_AMOUNT,SFQ_FEE_CODE ,SFQ_APPLY_TO_ACCOUNT,SFQ_PAID_DATE
 from [dbo].[PR1_STATEMENT_NEXT_FEE_Q]
 where 
 --SFQ_PAID_DATE  between @p_from and @p_to
  SFQ_FEE_CODE in(22 )
)*/
SELECT 
    'KGEMMHCA' AS Product,  
    POL_NUMBER AS [Policy Number],
    CONVERT(varchar, (ISNULL(BILLABD_ACCOUNTING_DATE, CAST(BILLABD_PAYMENT_DATE AS DATE))), 101) PAID_DATE,
     CONVERT(varchar, (ISNULL(last_p_term.POL_EFFECTIVE_DATE, CAST(last_p_term.POL_EFFECTIVE_DATE AS DATE))), 101) AS [Eff Date],
    (select TABLED_DESIGNATION from GN2_TABLED where TABLED_NAME = 'BATCHTYPE' and TABLED_LINGO = 2 and TABLED_CODE = BILLABD_BATCH_TYPE) as [Payment Type],
    CONVERT(varchar, (ISNULL(BILLABD_ACCOUNTING_DATE, CAST(BILLABD_PAYMENT_DATE AS DATE))), 101) AS [Transaction Date],
    (SELECT RTRIM(AGENT_NAME1 + ' ' +  AGENT_NAME2)
     FROM GN2_AGENT 
     WHERE AGENT_CODE = POLICY_INTERFACE_AGENTMASTER_CODE) AS [Agency],
    CASE is_renewal.HasRenewed 
        WHEN 1 THEN 'Renewal' 
        ELSE 'New' 
    END AS [New/Renewal],
    (SELECT FREQUENCY_DESCRIPTION  
     FROM [dbo].[PR2_FREQUENCY] 
     WHERE FREQUENCY_CODE = POL_PAY_PLAN) AS [Pay Plan],
     BILLBD_AMOUNT AS [Premium Received],
     ISNULL(inst_fees.FEE_TOTAL,0) AS [Installment Fee],
     ISNULL(policy_fees.FEE_TOTAL,0) AS [Policy Fee],
     ISNULL(mga_fees.FEE_TOTAL,0) AS [MGA Fee],
     ISNULL(figa_fees.FEE_TOTAL,0) AS [FIGA Fee],
     ISNULL(nsf_fees.FEE_TOTAL,0) AS [NSF Fee],
     ISNULL(empa_fees.FEE_TOTAL,0) AS [EMPA Fee],
      ISNULL(discount_fees1.FEE_TOTAL,0) AS [Insurance Premium Tax Relief Credit],
      ISNULL(discount_fees2.FEE_TOTAL,0) AS [State Fire Marshall Vill Credit],
	  ISNULL(stamping_Fee.SFQ_FEE_AMOUNT,0) AS [Stamping Fee],
	  ISNULL(surplus_line_tax.SFQ_FEE_AMOUNT,0) AS [SL Tax]
FROM PR1_BILLABD
JOIN PR1_ACCOUNTD 
    ON ACCOUNTD_NUMBER = BILLABD_ACCOUNT_NUMBER
JOIN PR1_ACCOUNTP 
    ON ACCOUNTP_NUMBER = ACCOUNTD_NUMBER
JOIN PR1_BILLBD
    ON BILLBD_REF_BATCH_SEQUENCE = BILLABD_SEQUENCE
AND BILLBD_REF_BATCH_LINE = BILLABD_LINE
AND BILLBD_REF_BATCH_TYPE = BILLABD_BATCH_TYPE
OUTER APPLY (
    SELECT TOP 1 POL_NUMBER, POL_EFFECTIVE_DATE, POL_PAY_PLAN
    FROM PR1_POLICY 
    WHERE POL_NUMBER = ACCOUNTP_POLICY_NUM
    ORDER BY POL_EFFECTIVE_DATE DESC
) last_p_term
OUTER APPLY (
    SELECT TOP 1 POLICY_INTERFACE_AGENTMASTER_CODE
    FROM UW1_POLICY_INTERFACE
    WHERE POL_NUMBER = POLICY_INTERFACE_POLICY_NUM 
          AND POL_EFFECTIVE_DATE = POLICY_INTERFACE_EFFECTIVE_DATE
    ORDER BY POLICY_INTERFACE_ENDORSEMENT_DATE DESC, POLICY_INTERFACE_ENDORSEMENT DESC
) last_pol_interface
OUTER APPLY (
    SELECT HasRenewed = 1
    FROM UW1_POLICY_INTERFACE
    WHERE POL_NUMBER = POLICY_INTERFACE_POLICY_NUM 
          AND POL_EFFECTIVE_DATE = POLICY_INTERFACE_EFFECTIVE_DATE
          AND POLICY_INTERFACE_STATUS_REASON = 5 /* Renewal */
) is_renewal
OUTER APPLY(    
    select FEE_TOTAL=sum(SF_AMOUNT)
    from [dbo].[PR1_STATEMENT_FEE] 
    where SF_FEE_CODE in (1,3) /*installment fee, eft fee*/
    and SF_STATEMENT_NUMBER = BILLBD_ACCOUNT_NUMBER
    and SF_PAID_DATE = BILLABD_ACCOUNTING_DATE
    and SF_PAID_DATE is not null    
    
)  inst_fees
OUTER APPLY(    
    select FEE_TOTAL=SUM(SFQ_FEE_AMOUNT)
    from [dbo].[PR1_STATEMENT_NEXT_FEE_Q]
    where SFQ_APPLY_TO_ACCOUNT = BILLABD_ACCOUNT_NUMBER
    and SFQ_PAID_DATE = BILLABD_ACCOUNTING_DATE
    and SFQ_PAID_DATE is not null
    and SFQ_FEE_CODE = 22 
)  policy_fees
OUTER APPLY(    
    
    select FEE_TOTAL=SUM(SFQ_FEE_AMOUNT)
    from [dbo].[PR1_STATEMENT_NEXT_FEE_Q]
    where SFQ_APPLY_TO_ACCOUNT = BILLABD_ACCOUNT_NUMBER
    and SFQ_PAID_DATE = BILLABD_ACCOUNTING_DATE
    and SFQ_PAID_DATE is not null
    and SFQ_FEE_CODE = 38 
)  mga_fees
OUTER APPLY(    
    
    select FEE_TOTAL=SUM(SFQ_FEE_AMOUNT)
    from [dbo].[PR1_STATEMENT_NEXT_FEE_Q]
    where SFQ_APPLY_TO_ACCOUNT = BILLABD_ACCOUNT_NUMBER
    and SFQ_PAID_DATE = BILLABD_ACCOUNTING_DATE
    and SFQ_PAID_DATE is not null
    and SFQ_FEE_CODE in(36,37,39) 
)  figa_fees
OUTER APPLY(    
    
    select FEE_TOTAL=SUM(SFQ_FEE_AMOUNT)
    from [dbo].[PR1_STATEMENT_NEXT_FEE_Q]
    where SFQ_APPLY_TO_ACCOUNT = BILLABD_ACCOUNT_NUMBER
    and SFQ_PAID_DATE = BILLABD_ACCOUNTING_DATE
    and SFQ_PAID_DATE is not null
    and SFQ_FEE_CODE = 2 
)  nsf_fees
OUTER APPLY(    
    
    select FEE_TOTAL=SUM(SFQ_FEE_AMOUNT)
    from [dbo].[PR1_STATEMENT_NEXT_FEE_Q]
    where SFQ_APPLY_TO_ACCOUNT = BILLABD_ACCOUNT_NUMBER
    and SFQ_PAID_DATE is not null
    and SFQ_PAID_DATE = BILLABD_ACCOUNTING_DATE
    and SFQ_FEE_CODE = 40 /* CHANGED */
)  empa_fees
OUTER APPLY(    
    
    select FEE_TOTAL=SUM(SFQ_FEE_AMOUNT)
    from [dbo].[PR1_STATEMENT_NEXT_FEE_Q]
    where SFQ_APPLY_TO_ACCOUNT = BILLABD_ACCOUNT_NUMBER
    and SFQ_PAID_DATE = BILLABD_ACCOUNTING_DATE
    and SFQ_PAID_DATE is not null
    and SFQ_FEE_CODE in  (62,63) 
)  discount_fees1
OUTER APPLY(    
    
    select FEE_TOTAL=SUM(SFQ_FEE_AMOUNT)
    from [dbo].[PR1_STATEMENT_NEXT_FEE_Q]
    where SFQ_APPLY_TO_ACCOUNT = BILLABD_ACCOUNT_NUMBER
    and SFQ_PAID_DATE = BILLABD_ACCOUNTING_DATE
    and SFQ_PAID_DATE is not null
    and SFQ_FEE_CODE in (60,61) 
)  discount_fees2
OUTER APPLY(
--Stamping Fee
select SFQ_FEE_AMOUNT = SUM(SFQ_FEE_AMOUNT)
from PR1_STATEMENT_NEXT_FEE_Q fq
where SFQ_IS_VALID = 1
and SFQ_PAID_DATE = BILLABD_ACCOUNTING_DATE
and  SFQ_APPLY_TO_ACCOUNT = BILLABD_ACCOUNT_NUMBER 
and SFQ_FEE_CODE = 11 --Stamping Fee
)  stamping_Fee
 
--Surplus Line Tax
OUTER APPLY(
select SFQ_FEE_AMOUNT = SUM(SFQ_FEE_AMOUNT)
from PR1_STATEMENT_NEXT_FEE_Q fq
where SFQ_IS_VALID = 1
and SFQ_PAID_DATE = BILLABD_ACCOUNTING_DATE
and  SFQ_APPLY_TO_ACCOUNT = BILLABD_ACCOUNT_NUMBER 
and SFQ_FEE_CODE = 10 --Surplus Line Tax 
) surplus_line_tax
WHERE 1=1
    AND ISNULL(BILLABD_AMOUNT_PAID, 0) <> 0
    AND BILLABD_BATCH_TYPE IN ('ACH', 'LB', 'ET', 'CFR', 'EPX', 'MTV', 'ORS', 'ASW', 'CAP', 'RDS')
